### ISSUE TITLE
CLIMenu doesn't support \s for arguments

### ISSUE THREAD

**Issue by pacotine** [pacotine/JSS#6]
"1. switch affectations between 2 settlers" selected :
Dartagnan 'Dark Vador' => should return 2 arguments (Dartagnan and Dark Vador), but it returns 3.

**Comment by lilBchii** [comment]
try '([^']+)'|\w+ 
with Matcher .group() method

https://regex101.com/r/yGlUOs/1

**Comment by pacotine** [comment]
I've found this one : `'([^']*)'|(\S+)`
match _zero or more_ character different from `'` **or** match _zero or more_ non-space characters.
Check this out : https://regex101.com/r/fOal4f/1

If I use your `group()` method, `readArguments(int n)` should look like this : 
```java
/**
 * Reads the next line and returns an array of {@code n} arguments (separated words by a space).
 * Handles arguments enclosed in single quotes.
 * @param n the number of arguments to read
 * @return an array of {@code n} arguments
 * @throws InputException if the input doesn't contain exactly {@code n} arguments
 */
public String[] readArguments(int n) throws InputException {
    String input = readInput();

    Matcher matcher = Pattern.compile("'([^']*)'|(\\S+)").matcher(input);
    List<String> args = new ArrayList<>();

    String gr;
    while (matcher.find()) {
        if((gr = matcher.group(1)) != null) { //group with single quotes
            args.add(gr);
        } else if((gr = matcher.group(2)) != null) { //group with simple space
            args.add(gr);
        }
    }

    if (args.size() != n) throw new InputException(
                "Input should have " + n + " arguments (" + args.size() + " given)",
                args.toString()
    );

    return args.toArray(new String[0]);
}
```

If it's ok for you, we can close this issue.

**Comment by lilBchii** [comment]
Yes, it seems to work after a few tests on it.

Even if you forget a space when you put `'`
```
'Dark Vador'Dartagnan
```
```
'Dartagnan''Dark Vador'
```

**Comment by pacotine** [comment]
Then `'([^']*)'(?!\S)|(\S+)` should work by forcing a space after a single quote `'` (`?!\S` checks if there is no non-space character).

```
'darth vader' yoda 'baby yoda' anakin => returns ["darth vader", "yoda", "baby yoda", "anakin"]
'darth vader' 'yoda' 'baby yoda' 'anakin' => returns ["darth vader", "yoda", "baby yoda", "anakin"]
'darth vader' 'baby yoda' => returns ["darth vader", "baby yoda"]
yoda anakin => returns ["yoda", "anakin"]
'group 1' group_2 => returns ["group 1", "groupe_2"]

'this' 'should' work => returns ["this", "should","work"]
'but''this' should 'not' => returns ["'but''this'", "should", "not"] because there is no space between 'but' and 'this'
```

https://regex101.com/r/WL7nnW/1

**Comment by pacotine** [comment]
I think it's better to forbid the possibility of two arguments stuck together. The instructions ask us to separate arguments with spaces, so we should stick to this idea and force a space between each argument, regardless of the type (between single quotes or simple).

**Comment by pacotine** [comment]
Fixed : https://github.com/pacotine/JSS/commit/2f50cda14f40cb171647a666433a735bc147a954
